site_name: Razon
site_url: https://mihailkovachev.github.io/Razon/
site_description: Razon is a comprehensive, community-driven knowledge repository designed for self-learners as a bridge between abstract theory and practical application. From the foundations of Ancient Greek to the algorithms of Modern Cryptography, explore a 'City of Knowledge' built to democratize education.

repo_url: https://github.com/MihailKovachev/Razon
repo_name: Razon

copyright: Copyright &copy; 2026 <a href="https://github.com/MihailKovachev">Mihail Kovachev</a>. All rights reserved.

docs_dir: vault

markdown_extensions:
  - nl2br
  - admonition
  - tables
  - def_list
  - sane_lists
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true

plugins:
  - search
  - callouts
  - tags
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0/tex-mml-chtml.js

theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: slate
      primary: custom
      accent: custom

extra_css:
  - assets/stylesheets/extra.css

validation:
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore